# Generated by Django 3.2 on 2021-04-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_ROLE', models.CharField(choices=[('Supervisor', 'Supe'), ('Instructor', 'Ins'), ('TA', 'Ta')], default='TA', max_length=12)),
                ('EMP_LNAME', models.CharField(max_length=25)),
                ('EMP_FNAME', models.CharField(max_length=25)),
                ('EMP_INITIAL', models.CharField(max_length=1)),
                ('EMP_EMAIL', models.EmailField(max_length=254)),
                ('EMP_PASSWORD', models.CharField(max_length=20)),
            ],
        ),
    ]
