# Generated by Django 3.2 on 2021-04-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMP_LNAME', models.CharField(max_length=25)),
                ('EMP_FNAME', models.CharField(max_length=25)),
                ('EMP_INITIAL', models.CharField(max_length=1)),
                ('EMP_EMAIL', models.EmailField(max_length=254)),
                ('EMP_DEPARTMENT', models.CharField(max_length=30)),
            ],
        ),
    ]
