# Generated by Django 3.2 on 2021-04-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EMP_ROLE',
            field=models.CharField(choices=[('TA', 'Ta'), ('Instructor', 'Ins')], default='TA', max_length=12),
        ),
    ]
