# Generated by Django 3.2 on 2021-04-23 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_employee_emp_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
