# Generated by Django 3.2 on 2021-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0006_auto_20210423_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(max_length=6, unique=True)),
                ('fName', models.CharField(max_length=25)),
                ('lName', models.CharField(max_length=25)),
                ('middleInitial', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=30)),
                ('type', models.IntegerField(choices=[('0', 'Supervisor'), ('1', 'Instructor'), ('2', 'Ta')], max_length=1)),
            ],
        ),
    ]
