# Generated by Django 3.2 on 2021-04-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='type',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.IntegerField(choices=[('0', 'Supervisor'), ('1', 'Instructor'), ('2', 'Ta')], default='2'),
        ),
    ]
