# Generated by Django 3.2 on 2021-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_auto_20210423_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('0', 'Supervisor'), ('1', 'Instructor'), ('2', 'Ta')], default='2', max_length=25),
        ),
    ]
